### ISSUE TITLE
Plugin should remember tags when navigating backwards into it

### ISSUE THREAD

**Issue by uwidev** [alexobenauer/Cross-reference-Navigation-for-Obsidian#3]
With the plugin open an as the currently active window, it will replace this pane with the note you clicked on. Pressing mouse navigate back will bring you all the way back to the "Home" for the plugin. If you navigated deep into your tags, you have to go back there again.

The plugin should remember it's navigation history on its panel when replaced with another note. A workaround would be to always open notes in a new pane, which functionality is not implemented either (ctrl+clicking does not open a new pane).

**Comment by pjeby** [comment]
The simplest way to implement this is probably with the `getEphemeralState()` and `setEphemeralState()` methods on the view object: return a JSON-serializable object from `getEphemeralState()` representing the current display state, and accept such an object in `setEphemeralState()`.  With that done, Obsidian will save the view state once every second, and it will also be persisted to the current workspace so it will be in that state if you restart Obsidian or switch between workspaces.

You can also call `app.workspace.requestSaveHistory()` to ask Obsidian to save your view state sooner than the next 1 second interval, and `app.workspace.requestSaveLayout()` to ask Obsidian to save the workspace as a whole.  (These requests will cause Obsidian to call back into your `getState()` and `getEphemeralState()` methods so it can serialize to history or disk.)

If I understand the plugin correctly, it seems that `getEphemeralState()` would just return an object with properties representing the  list of selected tags and expanded groups, and `setEphemeralState()` would apply it.  That would probably mean the Svelte component would need to export its tag menu store, which in turn would need to provide an interface to get and set both the selected tags and expanded groups.  The view would also need to subscribe to the store to know when to call `requestSaveHistory()`.

Also, from looking at the code, it appears the way the plugin currently handles opening new panes is to check for `metaKey` on the event, which I believe corresponds to the Windows key on Windows, or the Cmd key on Mac.  The correct way to check for an "open in new pane" click in Obsidian is to check `event.button == 1 || Keymap.isModifier(event, "Mod")`, as this will support both middle-clicking and cross-platform recognition of the correct modifier key.

**Comment by alexobenauer** [comment]
@blongty Agreed on this. Right now, meta key should open the new pane, but stay tuned for ctrl working.

@pjeby Appreciate the details. 

On the correct way to check for "open in new pane" — was there documentation somewhere on this that I missed?

**Comment by pjeby** [comment]
Documentation?  No, there's no documentation, just Discord.  :cry:  I figured out the Keymap thing by accident/reverse engineering, and the button == 1 part from Licat on Discord.

**Comment by alexobenauer** [comment]
@pjeby Thanks.

Implementing these changes now, but one thing - I'm unsure on where the `Keymap` object comes from?

**Comment by pjeby** [comment]
Huh.  That's weird.  I somehow never noticed it isn't listed in the API, despite being exported.  I'll put in a request for it to be documented since `isModifier()` is really the only safe/easy way to deal with cross-platform keyboard differences in events without needing to duplicate all of Obsidian's logic for that.

**Comment by alexobenauer** [comment]
Ah good to know! Appreciate it @pjeby.
