### ISSUE TITLE
Cross-Ref window not rendering

### ISSUE THREAD

**Issue by menagerie198** [alexobenauer/Cross-reference-Navigation-for-Obsidian#7]
Since Obsidian v0.12.19 (or Cross-Ref v0.3? - I updated both at the same time) Cross-Ref is not picking up any tags. I get a blank window, with "All Tags 0 notes" at the top, with "Favorite groups: ", and "Favorite tags: ", but nothing else. I get the same result in a vanilla test vault with no plugins, or snippets.
Deleting and reinstalling CrossRef gets it working again. But when I come back the next day/restart the above issue reappears.

**Comment by Borber** [comment]
I have this problem too

**Comment by alexobenauer** [comment]
Can you try toggling the plugin off in settings, then on again, and reload the cross-refs view?

**Comment by menagerie198** [comment]
Yes, that gets CrossRef back. With the BRAT plugin's new plugin-management functions, this is less of a pain than is would have been before. Still a pain tho. Hopefully this offers you some clues as to what is causing the disappearance of CrossRef?
